### ISSUE TITLE
is this tool still usable?

### ISSUE THREAD

**Issue by zhengyuan-ehps** [parrots-design/parrot-cd#2]
Hey,

I was using the latest version of this project to automate the plugin publish but failed to make it due to the authorized response from figma api by following the given docs to setup the env vars etc. 

so I just want to quickly checkin if this project still valid for the latest figma plugin publish workflow? if so can I get a latest document to follow?

Here is the current issue im encountering while running `figcd auth`:
```
yarn figcd auth                                                         [07/8/24 | 11:47:46]
yarn run v1.22.17
Please enter the email address of your Figma account: xxxx
Please enter your Figma password: xxxx

//....

SMS sent to number ending in (1077): please enter the Authentication code: 6371002

/Users/zheng.yuan/workspace/vega-figma/node_modules/figcd/src/auth-helper.js:145
        const cookiesReceived = loginResponse.headers.get('set-cookie').split('; ');
                                                                       ^

TypeError: Cannot read properties of null (reading 'split')
    at Command.authenticate (/Users/zheng.yuan/workspace/vega-figma/node_modules/figcd/src/auth-helper.js:145:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/Users/zheng.yuan/workspace/vega-figma/node_modules/figcd/node_modules/commander/lib/command.js:936:5)
    at async main (/Users/zheng.yuan/workspace/vega-figma/node_modules/figcd/bin/cli.js:135:9)

Node.js v20.10.0
```

Thanks

**Comment by macintoshhelper** [comment]
Hi, this issue should be resolved now. Can you test with the latest version?
